AWSTemplateFormatVersion: '2010-09-09'
Description: 'Um exemplo de template minimo: saídas'
Parameters:
  Environment:
    Description: Ambiente
    Type: String
    AllowedValues:
    - dev
    - hmg
    - prod
Resources:
  AwsUser:
    Type: AWS::IAM::User
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ['meubucketteste20180921-${Environment}', {Environment: !Ref 'Environment'}] 
Outputs:
  BucketName:
    Description: Nome do bucket
    Value: !Ref Bucket
  BucketArn:
    Description: Arn do bucket
    Value: !GetAtt [Bucket, Arn]
