AWSTemplateFormatVersion: '2010-09-09'
Description: 'Um exemplo de template minimo: usando valores exportados'
Parameters:
  BaseStackName:
    Description: Nome da stack que esta exportando o valor
    Type: String
Resources:
  BucketGroup:
    Type: AWS::IAM::Group
    Properties:
      Policies:
      - PolicyName: AllowAccessBucketPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:ListObjects
            - s3:ListBucket
            - s3:PutObject
            Resource: 
              - Fn::ImportValue: !Sub '${BaseStackName}-BucketArn' 