AWSTemplateFormatVersion: '2010-09-09'
Description: 'Um exemplo de template minimo: Usando um recurso customizado'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General
      Parameters:
      - Environment
    - Label:
        default: Array values
      Parameters:
      - Key1Value
      - Key2Value
      - Key3Value
Parameters:
  Environment:
    Description: Environment where the stack is being deployed
    Type: String
    AllowedValues:
    - qa
    - labs
    - hmg
    - prod
  Key1Value:
    Description: Value of key 1
    Type: String
  Key2Value:
    Description: Value of key 2
    Type: String
  Key3Value:
    Description: Value of key 3
    Type: String
Resources:
  MyCustomResourceUsing: 
    Type: "Custom::MyCustomResource"
    Version: "1.0"
    Properties: 
      ServiceToken: !Sub |
        arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:MyCustomResourceHandler
      Property1: "Value of property 1"
      Property2: !Ref 'Environment'
      ArrayProperty:
        - Key: "Key1"
          Value: !Ref Key1Value
        - Key: "Key2"
          Value: !Ref Key2Value
        - Key: "Key3"
          Value: !Ref Key3Value