AWSTemplateFormatVersion: '2010-09-09'
Description: 'Um exemplo de template minimo: propriedades'
Resources:
  AwsUser:
    Type: AWS::IAM::User
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "meubucketteste20180921"
